### ISSUE TITLE
Enable GC logging

### ISSUE THREAD

**Issue by uschi2000** [palantir/gradle-java-distribution#126] opened 2016-10-13 21:31 UTC
Something like

```
  launcherCustom:
    configType: java
    configVersion: 1
    jvmOpts:
      - '-XX:+PrintGCDateStamps'
      - '-XX:+PrintGCDetails'
      - '-XX:-TraceClassUnloading'
      - '-XX:+UseGCLogFileRotation'
      - '-XX:GCLogFileSize=10M'
      - '-XX:NumberOfGCLogFiles=10'
      - '-Xloggc:var/log/{{product_name}}.gc.log'
      - '-verbose:gc'
```

**Comment by ash211** [comment] 2016-10-13 23:25
Dupe of https://github.com/palantir/gradle-java-distribution/issues/121 but this has more specifics so closing that ticket

**Closed as completed** 2016-10-17 22:55 UTC
